view:
    fields:


     git_cppcomet_repo_url:
      title: "CppComet GIT"
      default: "https://github.com/CppComet/comet-server"
      format: string
      help: "CppComet GIT"

     git_branch:
      title: "branch"
      default: "master"
      format: string
      help: "GIT branch"

    playbooks:



     "highload-host.yml":
      title: "Make highload host"
      help: "Unset limits for opened connections"

     "update-cppcomet.yml":
      title: "Update CppComet"
      help: "Updates CppComet from GIT"