---
- hosts: all
  sudo: true
  vars:
    limits_conf_d_files:
      000-cppcomet-server.conf:
        - domain: root
          type: soft
          item: nofile
          value: 65535
        - domain: root
          type: hard
          item: nofile
          value: 65535
  roles:
    - ansible-role-highload
    - ansible-limits
  tasks: 
    - name: show limits
      raw: ulimit -a
      