---
# Обновляет комет сервер установленный командой make install
- hosts: all
  vars:
  remote_user: root
  tasks:

    - name: Update
      apt: update_cache=yes

    - name: Installing deps
      apt:
        name: curl,wget
        state: present

    - name: add nodejs
      shell:
        cmd: curl -sL https://deb.nodesource.com/setup_6.x | bash -

    - name: Update
      apt: update_cache=yes

    - name: Installing deps
      apt:
        name: cmake,make,cpp,gcc,libssl-dev,g++,nginx,pkg-config,libmariadbclient-dev-compat,mysql-client,flex,mailutils,uuid-dev,git,curl,wget,nodejs,build-essential,lcov,valgrind
        state: present

    - name: Make backup dir
      shell:
        cmd: mkdir /root/cppcomet-back  --parent

    - name: Config backup
      raw: date +"/root/cppcomet-back/cppcomet-%s" | xargs cp /usr/bin/cppcomet

    # Получение кода
    - name: Git clone
      raw: rm -rf /tmp/CppComet-last && mkdir /tmp/CppComet-last && cd /tmp/CppComet-last && git clone -q -b {{git_branch}} {{git_cppcomet_repo_url}} ./

    - name: Cmake Build
      shell:
        chdir: /tmp/CppComet-last
        cmd: cmake .


    - name: Make Build
      shell:
        chdir: /tmp/CppComet-last
        cmd: make

    - name: Config copy
      shell:
        cmd: cp /etc/comet-server/comet.ini /tmp/CppComet-last/comet.ini

    - name: Install
      shell:
        chdir: /tmp/CppComet-last
        cmd: make install

    - name: restart
      shell:
        cmd: service comet restart

    # Тесты версии
    - name: Add +x
      shell:
        cmd: chmod +x /tmp/CppComet-last/coverage/fulltests.sh

    - name: Installing deps
      shell:
        chdir: /tmp/CppComet-last/coverage
        cmd: npm install -g istanbul websocket mysql

    - name: Run tests
      shell:
        chdir: /tmp/CppComet-last/coverage
        cmd: ./onlyJsTests.sh > /tmp/last-js-test.log
      ignore_errors: yes

    - name: cat tests log
      raw: cat /tmp/last-js-test.log | grep -A 4 "Coverage summary"

