--- 
- name: Update
  apt: update_cache=yes

- name: Installing deps
  apt:
    name: cmake,make,cpp,gcc,libssl-dev,g++,nginx,pkg-config,libmariadbclient-dev-compat,mysql-client,flex,mailutils,uuid-dev,git,wget
    state: present
    
#- name: Clean CppComet dir
#  file:
#    state: absent
#    path: "/usr/src/cppcomet"
    
- name: Git clone CppComet
  git:
    repo: https://github.com/CppComet/comet-server
    dest: /usr/src/cppcomet
    version: "{{cppcomet_git_branch}}"
    force: yes

- name: cmake
  shell: cmake .
  args:
    chdir: /usr/src/cppcomet/

- name: make
  shell: make 
  args:
    chdir: /usr/src/cppcomet/

- name: make install
  shell: make install
  args:
    chdir: /usr/src/cppcomet/

- name: set comet.ini
  template:
    src: templates/comet.ini.j2
    dest: /etc/comet-server/comet.ini
     
- name: Start CppComet
  service:
    service: name=comet.service state=start

