# tasks file for limits
---
- name: configure pam files
  lineinfile:
    create: true
    dest: "{{ item }}"
    line: 'session required pam_limits.so'
  with_items: "{{ limits_pam_files }}"
  tags:
    - configuration
    - limits
    - limits-pam

- name: update configuration file(s)
  template:
    src: etc/security/limits.conf.j2
    dest: "/etc/security/limits.d/{{ item.key }}"
    owner: root
    group: root
    mode: 0644
  with_dict: "{{ limits_conf_d_files }}"
  tags:
    - configuration
    - limits
    - limits-configuration
