--- 
- name: Update
  apt: update_cache=yes

#- name: Installing deps
#  apt:
#    name: cmake,make,cpp,gcc,libssl-dev,g++,nginx,pkg-config,libmariadbclient-dev-compat,mysql-client,flex,mailutils,uuid-dev,git,wget
#    state: present
     
- name: copying conf dir 
  copy:
    src: templates/conf
    dest: /etc/freeswitch-video
    owner: root
    group: root
    mode: 0644
    
- name: set cpp_comet.xml
  template:
    src: templates/cpp_comet.xml.j2
    dest: /etc/freeswitch-video/cpp_comet.xml
     
     
# docker login  --password PW --username trapenokvictor
