# meta file for limits
---
galaxy_info:
  author: Mischa ter Smitten
  company: Oefenweb.nl B.V.
  description: Manage (security)limits in Debian-like systems
  license: MIT
  min_ansible_version: 2.2.0.0
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
    - name: Debian
      versions:
        - wheezy
        - jessie
  galaxy_tags:
    - system
    - monitoring
dependencies: []
