FROM debian:9
MAINTAINER Levhav@yandex.ru


RUN apt-get update && apt-get install --assume-yes cmake make cpp gcc libssl-dev g++ pkg-config libmariadbclient-dev-compat mysql-client flex mailutils uuid-dev git wget checkinstall
RUN git clone https://github.com/CppComet/comet-server  
#RUN cd /comet-server && cmake . && make
#RUN cd /comet-server && checkinstall  
 
#  cd /comet-server checkinstall --install=no -y --pkgname=CppComet --pkgversion=4.0.1 --pkgrelease=4 --pkglicense=AGPL --pkgsource=https://github.com/CppComet/comet-server

CMD ["/bin/bash"]

# This file used for building .deb package
# Build docker with command
# docker build --tag debian-install -f ./Dockerfile-debian .


# Start docker with command
# docker run -it debian-install:latest bash



# stop all containers:
# docker kill $(docker ps -q)

# remove all containers
# docker rm $(docker ps -a -q)

# remove all docker images
# docker rmi $(docker images -q)
