---
# Used only for Debian/Ubuntu installation, as the -t option for apt.


cppcomet_node_name: n1
cppcomet_useQueryLoger: false
cppcomet_base_dir: static
cppcomet_buf_size: 10384
cppcomet_fragment_buf_max_size: 10384
cppcomet_answer_buf_size: 1000000
cppcomet_db_host: localhost
cppcomet_db_user: comet
cppcomet_db_password: cometpassword
cppcomet_db_name: comet_db
cppcomet_db_port: 3306
cppcomet_ws_ip: 0.0.0.0
cppcomet_ws_thread_num: 4
cppcomet_statistics: 10
cppcomet_ws_port: 8087
cppcomet_cometql_ip: 0.0.0.0
cppcomet_cometql_thread_num: 4 
cppcomet_cometql_port: 3307
cppcomet_mysqlproxy_ip: 0.0.0.0
cppcomet_mysqlproxy_thread_num: 4
cppcomet_mysqlproxy_port: 3308
cppcomet_log_level: 200
cppcomet_password: root
cppcomet_fragment_buf_size: 600
cppcomet_git_branch: master
